
import fs from 'fs-extra';
import path from 'path';
import { logger } from '../../utils/logger';

export export interface
    domain: string;
    backendPort: number;
    enableCache: boolean;
    cacheSizeMB: number;
    enableSSL: boolean;
    certPath?: string;
    keyPath?: string;
}

export export interface
    compressionLevel: number; // 0-9
    compressionThreshold: number; // bytes
    enableRateLimiting: boolean;
    maxPacketsPerSecond: number;
}

const OUTPUT_DIR = path.join(process.cwd(), 'data', 'network');

export class NetworkConfigGenerator {
    
    constructor() {
        fs.ensureDirSync(OUTPUT_DIR);
        fs.ensureDirSync(path.join(OUTPUT_DIR, 'nginx'));
        fs.ensureDirSync(path.join(OUTPUT_DIR, 'velocity'));
    }

    /**
     * Generates a hardened NGINX configuration for Edge Caching and SSL Bridging.
     */
    public async generateNginxConfig(config: NginxEdgeConfig): Promise<string> {
        const { domain, backendPort, enableCache, cacheSizeMB, enableSSL, certPath, keyPath } = config;
        
        let nginxConf = `
# Generated by CraftCommand - Network Fabric
# Domain: ${domain}

${enableCache ? `proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=cc_edge_cache:10m max_size=${cacheSizeMB}m inactive=60m use_temp_path=off;` : ''}

server {
    listen 80;
    server_name ${domain};
    
    ${enableSSL ? 'return 301 https://$host$request_uri;' : `
    location / {
        proxy_pass http://127.0.0.1:${backendPort};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        ${enableCache ? 'proxy_cache cc_edge_cache; proxy_cache_valid 200 302 10m; add_header X-Cache-Status $upstream_cache_status;' : ''}
    }
    `}
}

${enableSSL && certPath && keyPath ? `
server {
    listen 443 ssl http2;
    server_name ${domain};

    ssl_certificate ${certPath};
    ssl_certificate_key ${keyPath};
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:${backendPort};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        ${enableCache ? 'proxy_cache cc_edge_cache; proxy_cache_valid 200 302 10m; add_header X-Cache-Status $upstream_cache_status;' : ''}
    }
}
` : ''}
`;

        const outputPath = path.join(OUTPUT_DIR, 'nginx', `${domain}.conf`);
        await fs.writeFile(outputPath, nginxConf.trim());
        logger.info(`[NetworkConfigGenerator] NGINX config generated for ${domain} at ${outputPath}`);
        return nginxConf;
    }

    /**
     * Generates advanced velocity filters and packet settings.
     */
    public async generateVelocityAdvancedConfig(proxyId: string, config: VelocityAdvancedConfig): Promise<string> {
        const { compressionLevel, compressionThreshold, enableRateLimiting, maxPacketsPerSecond } = config;
        
        // This generates a snippet that should be merged into velocity.toml or used by a plugin
        const tomlSnippet = `
# Velocity Advanced settings generated by CraftCommand

[advanced]
  compression-level = ${compressionLevel}
  compression-threshold = ${compressionThreshold}
  
[network]
  # Rate limiting logic (Assumes CC-Shield plugin or supported fork)
  enable-rate-limiting = ${enableRateLimiting}
  max-packets-per-second = ${maxPacketsPerSecond}
`;

        const outputPath = path.join(OUTPUT_DIR, 'velocity', `${proxyId}_advanced.toml`);
        await fs.writeFile(outputPath, tomlSnippet.trim());
        logger.info(`[NetworkConfigGenerator] Velocity advanced config generated for ${proxyId}`);
        return tomlSnippet;
    }
}

export const networkConfigGenerator = new NetworkConfigGenerator();
