import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import { logger } from '../../utils/logger';

export class HostPersistenceService {
    private static readonly WINDOWS_STARTUP_DIR = path.join(
        process.env.APPDATA || '',
        'Microsoft',
        'Windows',
        'Start Menu',
        'Programs',
        'Startup'
    );

    /**
     * Registers the CraftCommand Agent to start automatically when the OS boots.
     */
    public async enablePersistence(): Promise<boolean> {
        const platform = os.platform();

        try {
            if (platform === 'win32') {
                return await this.enableWindowsPersistence();
            } else if (platform === 'linux') {
                return await this.enableLinuxPersistence();
            } else if (platform === 'darwin') {
                return await this.enableMacOSPersistence();
            }
            throw new Error(`Platform ${platform} not supported for automatic persistence.`);
        } catch (error: unknown) {
            logger.error(`[HostPersistence] Failed to enable persistence: ${error.message}`);
            return false;
        }
    }

    /**
     * Removes the CraftCommand Agent from the OS startup sequence.
     */
    public async disablePersistence(): Promise<boolean> {
        const platform = os.platform();

        try {
            if (platform === 'win32') {
                const shortcutPath = path.join(HostPersistenceService.WINDOWS_STARTUP_DIR, 'CraftCommand_Agent.bat');
                if (await fs.pathExists(shortcutPath)) {
                    await fs.remove(shortcutPath);
                    logger.info('[HostPersistence] Disabled Windows Startup persistence.');
                }
                return true;
            } else if (platform === 'linux') {
                return await this.disableLinuxPersistence();
            } else if (platform === 'darwin') {
                return await this.disableMacOSPersistence();
            }
            return true;
        } catch (error: unknown) {
            logger.error(`[HostPersistence] Failed to disable persistence: ${error.message}`);
            return false;
        }
    }

    private async enableWindowsPersistence(): Promise<boolean> {
        if (!process.env.APPDATA) throw new Error('APPDATA environment variable missing.');
        
        const startupDir = HostPersistenceService.WINDOWS_STARTUP_DIR;
        const shortcutPath = path.join(startupDir, 'CraftCommand_Agent.bat');
        
        const startCommand = `cd /d "${process.cwd()}" && npm run start`;
        const content = `@echo off\nTITLE CraftCommand Agent\nREM Automatically generated by CraftCommand\n${startCommand}\n`;
        
        await fs.ensureDir(startupDir);
        await fs.writeFile(shortcutPath, content);
        
        logger.info(`[HostPersistence] Windows Startup shortcut created at ${shortcutPath}`);
        return true;
    }

    private async enableLinuxPersistence(): Promise<boolean> {
        const { exec } = require('child_process');
        const command = `(crontab -l 2>/dev/null; echo "@reboot cd ${process.cwd()} && npm run start # CraftCommand") | crontab -`;
        
        return new Promise((resolve) => {
            exec(command, (error: unknown) => {
                if (error) {
                    logger.error(`[HostPersistence] Linux crontab update failed: ${error.message}`);
                    resolve(false);
                } else {
                    logger.info('[HostPersistence] Linux @reboot persistence enabled via crontab.');
                    resolve(true);
                }
            });
        });
    }

    private async disableLinuxPersistence(): Promise<boolean> {
        const { exec } = require('child_process');
        const command = `crontab -l 2>/dev/null | grep -v "# CraftCommand" | crontab -`;
        
        return new Promise((resolve) => {
            exec(command, (error: unknown) => {
                if (error) {
                    logger.error(`[HostPersistence] Linux crontab cleanup failed: ${error.message}`);
                    resolve(false);
                } else {
                    logger.info('[HostPersistence] Linux crontab entry removed.');
                    resolve(true);
                }
            });
        });
    }

    private async enableMacOSPersistence(): Promise<boolean> {
        const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'io.craftcommand.agent.plist');
        const content = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.craftcommand.agent</string>
    <key>ProgramArguments</key>
    <array>
        <string>${process.execPath}</string>
        <string>${path.join(process.cwd(), 'node_modules', 'npm', 'bin', 'npm-cli.js')}</string>
        <string>run</string>
        <string>start</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>${process.cwd()}</string>
    <key>StandardOutPath</key>
    <string>${path.join(process.cwd(), 'persistence.log')}</string>
    <key>StandardErrorPath</key>
    <string>${path.join(process.cwd(), 'persistence.log')}</string>
</dict>
</plist>`;

        await fs.ensureDir(path.dirname(plistPath));
        await fs.writeFile(plistPath, content);
        logger.info(`[HostPersistence] MacOS LaunchAgent created at ${plistPath}`);
        return true;
    }

    private async disableMacOSPersistence(): Promise<boolean> {
        const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'io.craftcommand.agent.plist');
        if (await fs.pathExists(plistPath)) {
            await fs.remove(plistPath);
            logger.info('[HostPersistence] MacOS LaunchAgent removed.');
        }
        return true;
    }

    public async isPersistenceEnabled(): Promise<boolean> {
        const platform = os.platform();
        if (platform === 'win32') {
            return await fs.pathExists(path.join(HostPersistenceService.WINDOWS_STARTUP_DIR, 'CraftCommand_Agent.bat'));
        } else if (platform === 'darwin') {
            const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'io.craftcommand.agent.plist');
            return await fs.pathExists(plistPath);
        } else if (platform === 'linux') {
            const { execSync } = require('child_process');
            try {
                const stdout = execSync('crontab -l 2>/dev/null').toString();
                return stdout.includes('# CraftCommand');
            } catch (e) {
                return false;
            }
        }
        return false;
    }

    /**
     * Performs a deep diagnostic of the persistence state.
     * Returns: 
     * - OK: Registered and points to current folder.
     * - PATH_DRIFT: Registered but points to a different location.
     * - UNREGISTERED: No persistence entry found.
     * - ERROR: Diagnostic failed (usually permission issues).
     */
    public async getPersistenceStatus(): Promise<'OK' | 'PATH_DRIFT' | 'UNREGISTERED' | 'ERROR'> {
        try {
            const enabled = await this.isPersistenceEnabled();
            if (!enabled) return 'UNREGISTERED';

            const platform = os.platform();
            const  '';

            if (platform === 'win32') {
                const shortcutPath = path.join(HostPersistenceService.WINDOWS_STARTUP_DIR, 'CraftCommand_Agent.bat');
                const content = await fs.readFile(shortcutPath, 'utf8');
                // Simple extraction of the path from the bat file
                if (content.includes(process.cwd())) return 'OK';
                return 'PATH_DRIFT';
            } else if (platform === 'darwin') {
                const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'io.craftcommand.agent.plist');
                const content = await fs.readFile(plistPath, 'utf8');
                if (content.includes(process.cwd())) return 'OK';
                return 'PATH_DRIFT';
            } else if (platform === 'linux') {
                const { execSync } = require('child_process');
                const stdout = execSync('crontab -l 2>/dev/null').toString();
                if (stdout.includes(process.cwd())) return 'OK';
                return 'PATH_DRIFT';
            }
            
            return 'OK'; // Fallback
        } catch (error: unknown) {
            logger.error(`[HostPersistence] Status diagnostic failed: ${error.message}`);
            return 'ERROR';
        }
    }

    /**
     * Checks if the persistence entry correctly points to the current installation.
     * If there's a drift (e.g. folder moved), it re-registers itself.
     */
    public async verifyPersistencePath(): Promise<void> {
        const enabled = await this.isPersistenceEnabled();
        if (!enabled) return;

        const platform = os.platform();
        try {
            if (platform === 'win32') {
                const shortcutPath = path.join(HostPersistenceService.WINDOWS_STARTUP_DIR, 'CraftCommand_Agent.bat');
                const content = await fs.readFile(shortcutPath, 'utf8');
                if (!content.includes(process.cwd())) {
                    logger.warn(`[HostPersistence] Path drift detected. Re-registering Windows persistence.`);
                    await this.enableWindowsPersistence();
                }
            } else if (platform === 'darwin') {
                const plistPath = path.join(os.homedir(), 'Library', 'LaunchAgents', 'io.craftcommand.agent.plist');
                const content = await fs.readFile(plistPath, 'utf8');
                if (!content.includes(process.cwd())) {
                    logger.warn(`[HostPersistence] Path drift detected. Re-registering MacOS persistence.`);
                    await this.enableMacOSPersistence();
                }
            } else if (platform === 'linux') {
                const { execSync } = require('child_process');
                const stdout = execSync('crontab -l 2>/dev/null').toString();
                if (!stdout.includes(process.cwd())) {
                    logger.warn(`[HostPersistence] Path drift detected. Re-registering Linux persistence.`);
                    await this.enableLinuxPersistence();
                }
            }
        } catch (error: unknown) {
            logger.error(`[HostPersistence] Verification failed: ${error.message}`);
        }
    }
}

export const hostPersistenceService = new HostPersistenceService();
